[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-tungstenite = "*"
futures-channel = "0.3.31"
futures-util = "0.3.31"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }